#! /bin/bash
files=`find . -type f | egrep '\.geo\.json$'`
fail_count=0
file_count=0

for file in $files
do

    (( file_count += 1 ))
    result=$(curl -X POST --data @$file $data http://geojsonlint.com/validate 2>/dev/null)
    status=`echo $result | cut -d'"' -f4`

    if [ "$status" = "ok" ]; then
        echo "Valid GeoJSON for (" $file ")"
    else
	error=`echo $result | cut -d'"' -f8`
        echo "Invalid GeoJSON for (" $file ")"
        echo "Reason: " $error
      ((file_count +=1 ))
    fi
done

echo $file_count files checked. $fail_count failures.

if [ "$fail_count" = 0 ]; then
    exit 0
else
    exit 1
fi
